---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: certalert
  namespace: certalert
  labels:
    app: certalert
spec:
  endpoints:
  - interval: 60s
    port: http
  namespaceSelector:
    matchNames:
    - certalert
  selector:
    matchLabels:
      app: certalert
